site_name: ApacheCN - 可能是东半球最大的 AI 社区
site_url: https://www.apachecn.org
repo_url: https://github.com/apachecn/home

theme:
    name: null
    custom_dir: basic_theme

nav:
    - Home: index.md
    - About: about.md
    - Cooperate: cooperate.md
    - BBS: bbs.md
    - 404: 404.md
    - Join: join.md

