site_name: ApacheCN
site_description: ApacheCN 专注于优秀项目维护的开源组织
site_author: ApacheCN Team
site_keywords: 数据科学,数据分析,机器学习,人工智能,深度学习,推荐系统,NLP,CV,回归,分类,聚类,降维,朴素贝叶斯,决策树,SVM,KMeans,PCA,SVD,Logistic,DNN,CNN,LSTM,RNN,GAN,自编码器,sklearn,scikit-learn,TensorFlow,PyTorch,Python,NumPy,Matplotlib,Pandas

repo_url: https://github.com/apachecn/home
repo_name: GitHub

nav:
- 布客: https://www.ibooker.org.cn/
- 公告: info.md
- 知识树: https://github.com/apachecn/ai-roadmap/tree/master/v1.0
- 文档: docs/README.md
- 论坛: https://www.ibooker.org.cn/forums/
- 学习: learn/README.md
- 比赛: game/README.md
- 咨询: map/README.md
- 电子书: https://it-ebooks.flygon.net
- 组织:
    - 关于: about.md
    - 成员: https://www.ibooker.org.cn/organization/
    - 众筹: https://t.modian.com/project/67957.html
    - 捐赠记录: donate/README.md

theme:
    name: mkdocs
    custom_dir: 'custom_theme/'

# theme: readthedocs
# theme: bootstrap
# theme: amelia
# theme: cosmo
# theme: slate
# theme: yeti
# theme: united
# theme: journal

google_analytics: ['UA-127082511-1', 'apachecn.org']

plugins:
    - search
